# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.18.3"

default_platform :ios

platform :ios do

  product_name = "MultifonRedirect"
  env_build_dir = ENV["BUILD_DIR"]
  build_dir = env_build_dir ? env_build_dir : "build"
  versioned_product_name = product_name + "-" + number_of_commits.to_s
  archive_path = build_dir + "/" + versioned_product_name
  derived_data_path = build_dir + "/DerivedData"

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    setup_jenkins(derived_data_path: derived_data_path, output_directory: build_dir, force: true)
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  private_lane :build_and_archive do |options|
    gym(
      scheme: product_name,
      output_name: versioned_product_name,
      archive_path: archive_path,
      clean: true
    )
  end
  
  lane :developer do |options|
  	build_and_archive
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|
    # match(type: "appstore") # more information: https://codesigning.guide
  	build_and_archive(options)
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do |options|
    # match(type: "appstore")
    # snapshot
  	build_and_archive(options)
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
