#! /bin/sh -xe

wd=$(dirname "$0")
srcroot="${wd:?}/.."

for suffix in "" "-MultifonOnly" "-PhoneOnly" "-PhoneAndMultifon"
do
	AppIcon="AppIcon${suffix}"
	svg="${wd:?}/${AppIcon:?}.svg"
	xcassets="${srcroot:?}"/MultifonRedirect/MultifonRedirect/Assets.xcassets
	AppIconSet="${xcassets:?}"/"${AppIcon:?}".appiconset
	mkdir -p "${AppIconSet:?}"
	for i in 20 29 40 58 60 76 80 87 120 152 167 180
	do
		svg2png -w $i "${svg:?}" > "${AppIconSet:?}"/"${AppIcon:?}"-${i}x${i}.png
	done
	if [ z"${suffix}" != "z" ]
	then
		for j in 60 120 180
		do
			svg2png -w 60 "${svg:?}" > MultifonRedirect/MultifonRedirect/AlternateAppIcons/"${AppIcon:?}".png
			svg2png -w 120 "${svg:?}" > MultifonRedirect/MultifonRedirect/AlternateAppIcons/"${AppIcon:?}"@2x.png
			svg2png -w 180 "${svg:?}" > MultifonRedirect/MultifonRedirect/AlternateAppIcons/"${AppIcon:?}"@3x.png
		done
		sed "s/AppIcon-/AppIcon${suffix}-/g" < "${xcassets:?}"/AppIcon.appiconset/Contents.json > "${AppIconSet:?}"/Contents.json
	else
		svg2png -w 1024 "${svg:?}" > "${AppIcon:?}"-1024x1024.png
	fi
done
for shorctcutSuffix in "-ActiveRoute" "-InactiveRoute" "-Login" "-Logout"
do
	icon="Shortcut${shorctcutSuffix}"
	svg="${wd:?}/${icon:?}.svg"
	xcassets="${srcroot:?}"/MultifonRedirect/MultifonRedirect/Assets.xcassets
	imageset="${xcassets:?}"/"${icon:?}".imageset
	mkdir -p "${imageset:?}"
	for i in 50 100 150
	do
		svg2png -w $i "${svg:?}" > "${imageset:?}"/"${icon:?}"-${i}x${i}.png
	done
done
